package br.gov.cultura.DitelAdm.model;
// Generated 24/08/2016 14:33:52 by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * AlocacaoUsuarioLinha generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "alocacao_usuario_linha", catalog = "diteladmdev")
public class AlocacaoUsuarioLinha implements java.io.Serializable {

	private Integer idAlocacaoUsuarioLinha;
	@JsonBackReference
	private Linha linha;
	@JsonBackReference
	private Usuario usuario;
	private Date dtDevolucao;
	private Date dtRecebimento;
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private Set<AlocacaoSei> alocacaoSeis = new HashSet(0);

	public AlocacaoUsuarioLinha() {
	}

	public AlocacaoUsuarioLinha(Linha linha, Usuario usuario, Date dtRecebimento) {
		this.linha = linha;
		this.usuario = usuario;
		this.dtRecebimento = dtRecebimento;
	}

	public AlocacaoUsuarioLinha(Linha linha, Usuario usuario, Date dtDevolucao, Date dtRecebimento,Set<AlocacaoSei> alocacaoSeis) {
		this.linha = linha;
		this.usuario = usuario;
		this.dtDevolucao = dtDevolucao;
		this.dtRecebimento = dtRecebimento;
		this.alocacaoSeis = alocacaoSeis;
	}

	@Override
	public String toString() {
	   return "[Id: " + idAlocacaoUsuarioLinha +", Linha: " + linha.getNumeroLinha() + ","
	   		+ " Plano da Linha: " + linha.getPlanoLinha() + ", Usuario: "+ usuario.getNomeUsuario() +", CPF: "+ usuario.getCpfUsuario() +
	   		",Cargo: "+ usuario.getCargoUsuario()+", DAS: "+usuario.getLimiteAtesto().getDasAtesto()+", Devolução: "+dtDevolucao+
	   		", Recebido: "+dtRecebimento+" ]";
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_alocacao_usuario_linha", unique = true, nullable = false)
	public Integer getIdAlocacaoUsuarioLinha() {
		return this.idAlocacaoUsuarioLinha;
	}

	public void setIdAlocacaoUsuarioLinha(Integer idAlocacaoUsuarioLinha) {
		this.idAlocacaoUsuarioLinha = idAlocacaoUsuarioLinha;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_linha", nullable = false)
	public Linha getLinha() {
		return this.linha;
	}

	public void setLinha(Linha linha) {
		this.linha = linha;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_devolucao", length = 19)
	public Date getDtDevolucao() {
		return this.dtDevolucao;
	}

	public void setDtDevolucao(Date dtDevolucao) {
		this.dtDevolucao = dtDevolucao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_recebido", nullable = false, length = 19)
	public Date getDtRecebimento() {
		return this.dtRecebimento;
	}

	public void setDtRecebimento(Date dtRecebimento) {
		this.dtRecebimento = dtRecebimento;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alocacaoUsuarioLinha")
	public Set<AlocacaoSei> getAlocacaoSeis() {
		return this.alocacaoSeis;
	}

	public void setAlocacaoSeis(Set<AlocacaoSei> alocacaoSeis) {
		this.alocacaoSeis = alocacaoSeis;
	}
}
