package br.gov.cultura.DitelAdm.model;
// Generated 17/08/2016 19:31:54 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlocacaoUsuarioLinhaId generated by hbm2java
 */
@Embeddable
public class AlocacaoUsuarioLinhaId implements java.io.Serializable {

	private int idAlocacaoUsuarioLinha;
	private int idUsuario;
	private int idLinha;

	public AlocacaoUsuarioLinhaId() {
	}

	public AlocacaoUsuarioLinhaId(int idAlocacaoUsuarioLinha, int idUsuario, int idLinha) {
		this.idAlocacaoUsuarioLinha = idAlocacaoUsuarioLinha;
		this.idUsuario = idUsuario;
		this.idLinha = idLinha;
	}

	@Column(name = "idAlocacao_usuario_linha", nullable = false)
	public int getIdAlocacaoUsuarioLinha() {
		return this.idAlocacaoUsuarioLinha;
	}

	public void setIdAlocacaoUsuarioLinha(int idAlocacaoUsuarioLinha) {
		this.idAlocacaoUsuarioLinha = idAlocacaoUsuarioLinha;
	}

	@Column(name = "idUsuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "idLinha", nullable = false)
	public int getIdLinha() {
		return this.idLinha;
	}

	public void setIdLinha(int idLinha) {
		this.idLinha = idLinha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlocacaoUsuarioLinhaId))
			return false;
		AlocacaoUsuarioLinhaId castOther = (AlocacaoUsuarioLinhaId) other;

		return (this.getIdAlocacaoUsuarioLinha() == castOther.getIdAlocacaoUsuarioLinha())
				&& (this.getIdUsuario() == castOther.getIdUsuario()) && (this.getIdLinha() == castOther.getIdLinha());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAlocacaoUsuarioLinha();
		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdLinha();
		return result;
	}

}
