package br.gov.cultura.DitelAdm.model;
// Generated 27/04/2017 16:07:37 by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.gov.cultura.DitelAdm.model.faturasV3.Resumo;

/**
 * AlocacaoFatura generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "alocacao_fatura", catalog = "dbditel")
public class AlocacaoFatura implements java.io.Serializable {

	private Integer idAlocacaoFatura;
	private Resumo resumo;
	private Alocacao alocacao;
	private boolean ressarcimento;

	public AlocacaoFatura() {
	}

	public AlocacaoFatura(boolean ressarcimento, Resumo resumo, Alocacao alocacao) {
		this.resumo = resumo;
		this.alocacao = alocacao;
		this.ressarcimento = ressarcimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_alocacao_fatura", unique = true, nullable = false)
	public Integer getIdAlocacaoFatura() {
		return this.idAlocacaoFatura;
	}

	public void setIdAlocacaoFatura(Integer idAlocacaoFatura) {
		this.idAlocacaoFatura = idAlocacaoFatura;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_resumo", nullable = false)
	public Resumo getResumo() {
		return this.resumo;
	}

	public void setResumo(Resumo resumo) {
		this.resumo = resumo;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_alocacao", nullable = false)
	public Alocacao getAlocacao() {
		return this.alocacao;
	}

	public void setAlocacao(Alocacao alocacao) {
		this.alocacao = alocacao;
	}
	
	@Column(name = "ressarcimento", nullable = false)
	public boolean isRessarcimento() {
		return this.ressarcimento;
	}

	public void setRessarcimento(boolean ressarcimento) {
		this.ressarcimento = ressarcimento;
	}

}
