package br.gov.cultura.DitelAdm.model;
// Generated 07/11/2016 17:41:47 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.gov.cultura.DitelAdm.model.faturasV3.Resumo;

/**
 * AlocacaoSei generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "alocacao_sei", catalog = "dbditel")
public class AlocacaoSei implements java.io.Serializable {

	private int idAlocacaoSei;
	private AlocacaoUsuarioLinha alocacaoUsuarioLinha;
	private Resumo resumo;
	private boolean ressarcimento;

	public AlocacaoSei() {
	}

	public AlocacaoSei(int idAlocacaoSei, AlocacaoUsuarioLinha alocacaoUsuarioLinha, Resumo resumo,
			String numeroProcessoSei, boolean ressarcimento) {
		this.idAlocacaoSei = idAlocacaoSei;
		this.alocacaoUsuarioLinha = alocacaoUsuarioLinha;
		this.resumo = resumo;
		this.ressarcimento = ressarcimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_alocacao_sei", unique = true, nullable = false)
	public int getIdAlocacaoSei() {
		return this.idAlocacaoSei;
	}

	public void setIdAlocacaoSei(int idAlocacaoSei) {
		this.idAlocacaoSei = idAlocacaoSei;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alocacao_usuario_linha_id_alocacao_usuario_linha", nullable = false)
	public AlocacaoUsuarioLinha getAlocacaoUsuarioLinha() {
		return this.alocacaoUsuarioLinha;
	}

	public void setAlocacaoUsuarioLinha(AlocacaoUsuarioLinha alocacaoUsuarioLinha) {
		this.alocacaoUsuarioLinha = alocacaoUsuarioLinha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resumo_id_resumo", nullable = false)
	public Resumo getResumo() {
		return this.resumo;
	}

	public void setResumo(Resumo resumo) {
		this.resumo = resumo;
	}

	@Column(name = "ressarcimento", nullable = false)
	public boolean isRessarcimento() {
		return this.ressarcimento;
	}

	public void setRessarcimento(boolean ressarcimento) {
		this.ressarcimento = ressarcimento;
	}

}
