package br.gov.cultura.DitelAdm.model;
// Generated 17/08/2016 19:31:54 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlocacaoLinhaChipId generated by hbm2java
 */
@Embeddable
public class AlocacaoLinhaChipId implements java.io.Serializable {

	private int idAlocacaoLinhaChip;
	private int idLinha;
	private int idChip;

	public AlocacaoLinhaChipId() {
	}

	public AlocacaoLinhaChipId(int idAlocacaoLinhaChip, int idLinha, int idChip) {
		this.idAlocacaoLinhaChip = idAlocacaoLinhaChip;
		this.idLinha = idLinha;
		this.idChip = idChip;
	}

	@Column(name = "idAlocacao_linha_chip", nullable = false)
	public int getIdAlocacaoLinhaChip() {
		return this.idAlocacaoLinhaChip;
	}

	public void setIdAlocacaoLinhaChip(int idAlocacaoLinhaChip) {
		this.idAlocacaoLinhaChip = idAlocacaoLinhaChip;
	}

	@Column(name = "idLinha", nullable = false)
	public int getIdLinha() {
		return this.idLinha;
	}

	public void setIdLinha(int idLinha) {
		this.idLinha = idLinha;
	}

	@Column(name = "idChip", nullable = false)
	public int getIdChip() {
		return this.idChip;
	}

	public void setIdChip(int idChip) {
		this.idChip = idChip;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlocacaoLinhaChipId))
			return false;
		AlocacaoLinhaChipId castOther = (AlocacaoLinhaChipId) other;

		return (this.getIdAlocacaoLinhaChip() == castOther.getIdAlocacaoLinhaChip())
				&& (this.getIdLinha() == castOther.getIdLinha()) && (this.getIdChip() == castOther.getIdChip());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAlocacaoLinhaChip();
		result = 37 * result + this.getIdLinha();
		result = 37 * result + this.getIdChip();
		return result;
	}

}
