package br.gov.cultura.DitelAdm.model;
// Generated 24/08/2016 14:33:52 by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlocacaoLinhaChip generated by hbm2java
 */
@Entity
@Table(name = "alocacao_linha_chip", catalog = "diteladmdev")
public class AlocacaoLinhaChip implements java.io.Serializable {

	private Integer idAlocacaoLinhaChip;
	private Chip chip;
	private Linha linha;
	private Date dtDevolucao;
	private Date dtRecebimento;

	public AlocacaoLinhaChip() {
	}

	public AlocacaoLinhaChip(Chip chip, Linha linha, Date dtRecebimento) {
		this.chip = chip;
		this.linha = linha;
		this.dtRecebimento = dtRecebimento;
	}

	public AlocacaoLinhaChip(Chip chip, Linha linha, Date dtDevolucao, Date dtRecebimento) {
		this.chip = chip;
		this.linha = linha;
		this.dtDevolucao = dtDevolucao;
		this.dtRecebimento = dtRecebimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_alocacao_linha_chip", unique = true, nullable = false)
	public Integer getIdAlocacaoLinhaChip() {
		return this.idAlocacaoLinhaChip;
	}

	public void setIdAlocacaoLinhaChip(Integer idAlocacaoLinhaChip) {
		this.idAlocacaoLinhaChip = idAlocacaoLinhaChip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chip", nullable = false)
	public Chip getChip() {
		return this.chip;
	}

	public void setChip(Chip chip) {
		this.chip = chip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_linha", nullable = false)
	public Linha getLinha() {
		return this.linha;
	}

	public void setLinha(Linha linha) {
		this.linha = linha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_devolucao", length = 19)
	public Date getDtDevolucao() {
		return this.dtDevolucao;
	}

	public void setDtDevolucao(Date dtDevolucao) {
		this.dtDevolucao = dtDevolucao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_recebimento", nullable = false, length = 19)
	public Date getDtRecebimento() {
		return this.dtRecebimento;
	}

	public void setDtRecebimento(Date dtRecebimento) {
		this.dtRecebimento = dtRecebimento;
	}

}
