package br.gov.cultura.DitelAdm.model;
// Generated 17/08/2016 19:31:54 by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlocacaoLinhaChip generated by hbm2java
 */
@Entity
@Table(name = "alocacao_linha_chip", catalog = "diteladmdev")
public class AlocacaoLinhaChip implements java.io.Serializable {

	private AlocacaoLinhaChipId id;
	private Chip chip;
	private Linha linha;
	private Date dtRecebimento;
	private Date dtDevolucao;

	public AlocacaoLinhaChip() {
	}

	public AlocacaoLinhaChip(AlocacaoLinhaChipId id, Chip chip, Linha linha, Date dtRecebimento) {
		this.id = id;
		this.chip = chip;
		this.linha = linha;
		this.dtRecebimento = dtRecebimento;
	}

	public AlocacaoLinhaChip(AlocacaoLinhaChipId id, Chip chip, Linha linha, Date dtRecebimento, Date dtDevolucao) {
		this.id = id;
		this.chip = chip;
		this.linha = linha;
		this.dtRecebimento = dtRecebimento;
		this.dtDevolucao = dtDevolucao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAlocacaoLinhaChip", column = @Column(name = "idAlocacao_linha_chip", nullable = false)),
			@AttributeOverride(name = "idLinha", column = @Column(name = "idLinha", nullable = false)),
			@AttributeOverride(name = "idChip", column = @Column(name = "idChip", nullable = false)) })
	public AlocacaoLinhaChipId getId() {
		return this.id;
	}

	public void setId(AlocacaoLinhaChipId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idChip", nullable = false, insertable = false, updatable = false)
	public Chip getChip() {
		return this.chip;
	}

	public void setChip(Chip chip) {
		this.chip = chip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLinha", nullable = false, insertable = false, updatable = false)
	public Linha getLinha() {
		return this.linha;
	}

	public void setLinha(Linha linha) {
		this.linha = linha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtRecebimento", nullable = false, length = 19)
	public Date getDtRecebimento() {
		return this.dtRecebimento;
	}

	public void setDtRecebimento(Date dtRecebimento) {
		this.dtRecebimento = dtRecebimento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtDevolucao", length = 19)
	public Date getDtDevolucao() {
		return this.dtDevolucao;
	}

	public void setDtDevolucao(Date dtDevolucao) {
		this.dtDevolucao = dtDevolucao;
	}

}
