package br.gov.cultura.DitelAdm.model;
// Generated 02/09/2016 17:32:27 by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlocacaoLinhaCategoria generated by hbm2java
 */
@Entity
@Table(name = "alocacao_linha_categoria", catalog = "diteladmdev")
public class AlocacaoLinhaCategoria implements java.io.Serializable {

	private Integer idAlocacaoLinhaCategoria;
	private Categoria categoria;
	private Linha linha;
	private Date dtDevolucao;
	private Date dtRecebimento;

	public AlocacaoLinhaCategoria() {
	}

	public AlocacaoLinhaCategoria(Categoria categoria, Linha linha, Date dtRecebimento) {
		this.categoria = categoria;
		this.linha = linha;
		this.dtRecebimento = dtRecebimento;
	}

	public AlocacaoLinhaCategoria(Categoria categoria, Linha linha, Date dtDevolucao, Date dtRecebimento) {
		this.categoria = categoria;
		this.linha = linha;
		this.dtDevolucao = dtDevolucao;
		this.dtRecebimento = dtRecebimento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_alocacao_linha_categoria", unique = true, nullable = false)
	public Integer getIdAlocacaoLinhaCategoria() {
		return this.idAlocacaoLinhaCategoria;
	}

	public void setIdAlocacaoLinhaCategoria(Integer idAlocacaoLinhaCategoria) {
		this.idAlocacaoLinhaCategoria = idAlocacaoLinhaCategoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria_id_categoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "linha_id_linha", nullable = false)
	public Linha getLinha() {
		return this.linha;
	}

	public void setLinha(Linha linha) {
		this.linha = linha;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_devolucao", length = 19)
	public Date getDtDevolucao() {
		return this.dtDevolucao;
	}

	public void setDtDevolucao(Date dtDevolucao) {
		this.dtDevolucao = dtDevolucao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_recebimento", nullable = false, length = 19)
	public Date getDtRecebimento() {
		return this.dtRecebimento;
	}

	public void setDtRecebimento(Date dtRecebimento) {
		this.dtRecebimento = dtRecebimento;
	}

}
