package br.gov.cultura.DitelAdm.model;
// Generated 17/08/2016 19:31:54 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlocacaoLinhaDispositivoId generated by hbm2java
 */
@Embeddable
public class AlocacaoLinhaDispositivoId implements java.io.Serializable {

	private int idAlocacaoLinhaDispositivo;
	private int linhaIdlinha;
	private int dispositivoIdDispositivo;

	public AlocacaoLinhaDispositivoId() {
	}

	public AlocacaoLinhaDispositivoId(int idAlocacaoLinhaDispositivo, int linhaIdlinha, int dispositivoIdDispositivo) {
		this.idAlocacaoLinhaDispositivo = idAlocacaoLinhaDispositivo;
		this.linhaIdlinha = linhaIdlinha;
		this.dispositivoIdDispositivo = dispositivoIdDispositivo;
	}

	@Column(name = "idAlocacao_linha_dispositivo", nullable = false)
	public int getIdAlocacaoLinhaDispositivo() {
		return this.idAlocacaoLinhaDispositivo;
	}

	public void setIdAlocacaoLinhaDispositivo(int idAlocacaoLinhaDispositivo) {
		this.idAlocacaoLinhaDispositivo = idAlocacaoLinhaDispositivo;
	}

	@Column(name = "linha_idlinha", nullable = false)
	public int getLinhaIdlinha() {
		return this.linhaIdlinha;
	}

	public void setLinhaIdlinha(int linhaIdlinha) {
		this.linhaIdlinha = linhaIdlinha;
	}

	@Column(name = "dispositivo_idDispositivo", nullable = false)
	public int getDispositivoIdDispositivo() {
		return this.dispositivoIdDispositivo;
	}

	public void setDispositivoIdDispositivo(int dispositivoIdDispositivo) {
		this.dispositivoIdDispositivo = dispositivoIdDispositivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlocacaoLinhaDispositivoId))
			return false;
		AlocacaoLinhaDispositivoId castOther = (AlocacaoLinhaDispositivoId) other;

		return (this.getIdAlocacaoLinhaDispositivo() == castOther.getIdAlocacaoLinhaDispositivo())
				&& (this.getLinhaIdlinha() == castOther.getLinhaIdlinha())
				&& (this.getDispositivoIdDispositivo() == castOther.getDispositivoIdDispositivo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAlocacaoLinhaDispositivo();
		result = 37 * result + this.getLinhaIdlinha();
		result = 37 * result + this.getDispositivoIdDispositivo();
		return result;
	}

}
