package br.gov.cultura.DitelAdm.model;
// Generated 27/04/2017 16:07:37 by Hibernate Tools 4.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DocumentosSei generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "documento_sei", catalog = "dbditel")
public class DocumentoSei implements java.io.Serializable {

	private Integer idDocumentosSei;
	@JsonBackReference
	private AlocacaoSei alocacaoSei;
	private String documentosTipo;
	private String documentosLink;
	private String documentoIdSei;
	private String documentosNumero;
	private Date documentosDataGerado;

	public DocumentoSei() {
	}

	public DocumentoSei(AlocacaoSei alocacaoSei, String documentosTipo, String documentosLink, String documentoIdSei, String documentosNumero,
			Date documentosDataGerado) {
		this.alocacaoSei = alocacaoSei;
		this.documentosTipo = documentosTipo;
		this.documentosLink = documentosLink;
		this.documentoIdSei = documentoIdSei;
		this.documentosNumero = documentosNumero;
		this.documentosDataGerado = documentosDataGerado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_documentos_sei", unique = true, nullable = false)
	public Integer getIdDocumentosSei() {
		return this.idDocumentosSei;
	}

	public void setIdDocumentosSei(Integer idDocumentosSei) {
		this.idDocumentosSei = idDocumentosSei;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_alocacao_sei", nullable = false)
	public AlocacaoSei getAlocacaoSei() {
		return this.alocacaoSei;
	}

	public void setAlocacaoSei(AlocacaoSei alocacaoSei) {
		this.alocacaoSei = alocacaoSei;
	}
	@Column(name = "documentos_tipo")
	public String getDocumentosTipo() {
		return this.documentosTipo;
	}

	public void setDocumentosTipo(String documentosTipo) {
		this.documentosTipo = documentosTipo;
	}
	@Column(name = "documentos_link")
	public String getDocumentosLink() {
		return this.documentosLink;
	}

	public void setDocumentosLink(String documentosLink) {
		this.documentosLink = documentosLink;
	}
	
	@Column(name = "documentos_id_sei")
	public String getDocumentoIdSei() {
		return documentoIdSei;
	}

	public void setDocumentoIdSei(String documentoIdSei) {
		this.documentoIdSei = documentoIdSei;
	}

	@Column(name = "documentos_numero")
	public String getDocumentosNumero() {
		return this.documentosNumero;
	}

	public void setDocumentosNumero(String documentosNumero) {
		this.documentosNumero = documentosNumero;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_recebido", nullable = false, length = 19)
	public Date getDocumentosDataGerado() {
		return this.documentosDataGerado;
	}

	public void setDocumentosDataGerado(Date documentosDataGerado) {
		this.documentosDataGerado = documentosDataGerado;
	}

}
