package br.gov.cultura.DitelAdm.model;
// Generated 05/09/2016 11:00:27 by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import br.gov.cultura.DitelAdm.model.faturasV3.Resumo;


/**
 * Linha generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "linha", catalog = "dbditel")
public class Linha implements java.io.Serializable {

	private Integer idLinha;
	private String numeroLinha;
	private String planoLinha;
	@SuppressWarnings({ "unchecked", "rawtypes" })
	@JsonManagedReference
	private Set<AlocacaoLinhaDispositivo> alocacaoLinhaDispositivos = new HashSet(0);
	@SuppressWarnings({ "unchecked", "rawtypes" })
	@JsonManagedReference
	private Set<AlocacaoLinhaCategoria> alocacaoLinhaCategorias = new HashSet(0);
	@SuppressWarnings({ "unchecked", "rawtypes" })
	@JsonManagedReference
	private Set<AlocacaoUsuarioLinha> alocacaoUsuarioLinhas = new HashSet(0);
	@SuppressWarnings({ "unchecked", "rawtypes" })
	@JsonManagedReference
	private Set<AlocacaoLinhaChip> alocacaoLinhaChips = new HashSet(0);
	@SuppressWarnings({ "unchecked", "rawtypes" })
	@JsonManagedReference
	private Set<Resumo> resumos = new HashSet(0);
	public Linha() {
	}

	public Linha(String numeroLinha) {
		this.numeroLinha = numeroLinha;
	}

	public Linha(String numeroLinha, String planoLinha, Set<AlocacaoLinhaDispositivo> alocacaoLinhaDispositivos, Set<AlocacaoLinhaCategoria> alocacaoLinhaCategorias,
			Set<AlocacaoUsuarioLinha> alocacaoUsuarioLinhas, Set<AlocacaoLinhaChip> alocacaoLinhaChips, Set<Resumo> resumos) {
		this.numeroLinha = numeroLinha;
		this.planoLinha = planoLinha;
		this.alocacaoLinhaDispositivos = alocacaoLinhaDispositivos;
		this.alocacaoLinhaCategorias = alocacaoLinhaCategorias;
		this.alocacaoUsuarioLinhas = alocacaoUsuarioLinhas;
		this.alocacaoLinhaChips = alocacaoLinhaChips;
		this.resumos = resumos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_linha", unique = true, nullable = false)
	public Integer getIdLinha() {
		return this.idLinha;
	}

	public void setIdLinha(Integer idLinha) {
		this.idLinha = idLinha;
	}

	@Column(name = "numero_linha", nullable = false, length = 17)
	public String getNumeroLinha() {
		return this.numeroLinha;
	}

	public void setNumeroLinha(String numeroLinha) {
		this.numeroLinha = numeroLinha;
	}

	@Column(name = "plano_linha", length = 45)
	public String getPlanoLinha() {
		return this.planoLinha;
	}

	public void setPlanoLinha(String planoLinha) {
		this.planoLinha = planoLinha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linha")
	public Set<AlocacaoLinhaDispositivo> getAlocacaoLinhaDispositivos() {
		return this.alocacaoLinhaDispositivos;
	}

	public void setAlocacaoLinhaDispositivos(Set<AlocacaoLinhaDispositivo> alocacaoLinhaDispositivos) {
		this.alocacaoLinhaDispositivos = alocacaoLinhaDispositivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linha")
	public Set<AlocacaoLinhaCategoria> getAlocacaoLinhaCategorias() {
		return this.alocacaoLinhaCategorias;
	}

	public void setAlocacaoLinhaCategorias(Set<AlocacaoLinhaCategoria> alocacaoLinhaCategorias) {
		this.alocacaoLinhaCategorias = alocacaoLinhaCategorias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linha")
	public Set<AlocacaoUsuarioLinha> getAlocacaoUsuarioLinhas() {
		return this.alocacaoUsuarioLinhas;
	}

	public void setAlocacaoUsuarioLinhas(Set<AlocacaoUsuarioLinha> alocacaoUsuarioLinhas) {
		this.alocacaoUsuarioLinhas = alocacaoUsuarioLinhas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linha")
	public Set<AlocacaoLinhaChip> getAlocacaoLinhaChips() {
		return this.alocacaoLinhaChips;
	}

	public void setAlocacaoLinhaChips(Set<AlocacaoLinhaChip> alocacaoLinhaChips) {
		this.alocacaoLinhaChips = alocacaoLinhaChips;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linha")
	public Set<Resumo> getResumos() {
		return this.resumos;
	}

	public void setResumos(Set<Resumo> resumos) {
		this.resumos = resumos;
	}

}
