package br.gov.cultura.DitelAdm.model;
// Generated 17/08/2016 19:31:54 by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.br.CPF;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "diteladmdev")
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private LimiteAtesto limiteAtesto;
	private String nomeUsuario;
	private String cpfUsuario;
	private String cargoUsuario;
	private String lotacaoUsuario;
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private Set<AlocacaoUsuarioLinha> alocacaoUsuarioLinhas = new HashSet(0);

	public Usuario() {
	}

	public Usuario(LimiteAtesto limiteAtesto, String nomeUsuario, String cpfUsuario, String cargoUsuario,
			String lotacaoUsuario) {
		this.limiteAtesto = limiteAtesto;
		this.nomeUsuario = nomeUsuario;
		this.cpfUsuario = cpfUsuario;
		this.cargoUsuario = cargoUsuario;
		this.lotacaoUsuario = lotacaoUsuario;
	}

	public Usuario(LimiteAtesto limiteAtesto, String nomeUsuario, String cpfUsuario, String cargoUsuario,
			String lotacaoUsuario, Set<AlocacaoUsuarioLinha> alocacaoUsuarioLinhas) {
		this.limiteAtesto = limiteAtesto;
		this.nomeUsuario = nomeUsuario;
		this.cpfUsuario = cpfUsuario;
		this.cargoUsuario = cargoUsuario;
		this.lotacaoUsuario = lotacaoUsuario;
		this.alocacaoUsuarioLinhas = alocacaoUsuarioLinhas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "limite_atesto_idLimite_atesto", nullable = false)
	public LimiteAtesto getLimiteAtesto() {
		return this.limiteAtesto;
	}

	public void setLimiteAtesto(LimiteAtesto limiteAtesto) {
		this.limiteAtesto = limiteAtesto;
	}

	@Column(name = "nomeUsuario", nullable = false)
	@NotEmpty(message="Descrição e obrigatório!")
	@Size(max = 100, message = "Maximo de 100 caracteres para descrição!")
	public String getNomeUsuario() {
		return this.nomeUsuario;
	}

	public void setNomeUsuario(String nomeUsuario) {
		this.nomeUsuario = nomeUsuario;
	}

	@Column(name = "cpfUsuario", nullable = false, length = 11)
	@CPF
	@NotNull(message="CPF e obrigatório!")
	public String getCpfUsuario() {
		return this.cpfUsuario;
	}

	public void setCpfUsuario(String cpfUsuario) {
		this.cpfUsuario = cpfUsuario;
	}

	@Column(name = "cargoUsuario", nullable = false)
	public String getCargoUsuario() {
		return this.cargoUsuario;
	}

	public void setCargoUsuario(String cargoUsuario) {
		this.cargoUsuario = cargoUsuario;
	}

	@Column(name = "lotacaoUsuario", nullable = false)
	@NotNull(message = "Campo lotação e obrigatório!")
	public String getLotacaoUsuario() {
		return this.lotacaoUsuario;
	}

	public void setLotacaoUsuario(String lotacaoUsuario) {
		this.lotacaoUsuario = lotacaoUsuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<AlocacaoUsuarioLinha> getAlocacaoUsuarioLinhas() {
		return this.alocacaoUsuarioLinhas;
	}

	public void setAlocacaoUsuarioLinhas(Set<AlocacaoUsuarioLinha> alocacaoUsuarioLinhas) {
		this.alocacaoUsuarioLinhas = alocacaoUsuarioLinhas;
	}

}
