package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ajustes generated by hbm2java
 */
@Entity
@Table(name = "ajustes", catalog = "diteladmdev")
public class Ajustes implements java.io.Serializable {

	private AjustesId id;
	private Categoriaajuste categoriaajuste;
	private Resumo resumo;
	private String tipo;
	private float baseCalculo;
	private float percentual;
	private String sinal;
	private float valor;
	private Date dataFim;
	private Date horaFim;
	private String campoLivreOp;

	public Ajustes() {
	}

	public Ajustes(AjustesId id, Categoriaajuste categoriaajuste, Resumo resumo, String tipo, float baseCalculo,
			float percentual, String sinal, float valor) {
		this.id = id;
		this.categoriaajuste = categoriaajuste;
		this.resumo = resumo;
		this.tipo = tipo;
		this.baseCalculo = baseCalculo;
		this.percentual = percentual;
		this.sinal = sinal;
		this.valor = valor;
	}

	public Ajustes(AjustesId id, Categoriaajuste categoriaajuste, Resumo resumo, String tipo, float baseCalculo,
			float percentual, String sinal, float valor, Date dataFim, Date horaFim, String campoLivreOp) {
		this.id = id;
		this.categoriaajuste = categoriaajuste;
		this.resumo = resumo;
		this.tipo = tipo;
		this.baseCalculo = baseCalculo;
		this.percentual = percentual;
		this.sinal = sinal;
		this.valor = valor;
		this.dataFim = dataFim;
		this.horaFim = horaFim;
		this.campoLivreOp = campoLivreOp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAjustes", column = @Column(name = "idAjustes", nullable = false)),
			@AttributeOverride(name = "categoriaAjusteCodCatAjuste", column = @Column(name = "categoriaAjuste_codCatAjuste", nullable = false)),
			@AttributeOverride(name = "dataInicio", column = @Column(name = "dataInicio", nullable = false, length = 10)),
			@AttributeOverride(name = "horaInicio", column = @Column(name = "horaInicio", nullable = false, length = 19)) })
	public AjustesId getId() {
		return this.id;
	}

	public void setId(AjustesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoriaAjuste_codCatAjuste", nullable = false, insertable = false, updatable = false)
	public Categoriaajuste getCategoriaajuste() {
		return this.categoriaajuste;
	}

	public void setCategoriaajuste(Categoriaajuste categoriaajuste) {
		this.categoriaajuste = categoriaajuste;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "resumo_id", referencedColumnName = "id", nullable = false),
			@JoinColumn(name = "resumo_numRecurso", referencedColumnName = "numRecurso", nullable = false),
			@JoinColumn(name = "resumo_fatura_numFatura", referencedColumnName = "fatura_numFatura", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_codCliente", referencedColumnName = "fatura_cliente_codCliente", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_operadora_codOperadora", referencedColumnName = "fatura_cliente_operadora_codOperadora", nullable = false),
			@JoinColumn(name = "resumo_fatura_dataEmissao", referencedColumnName = "fatura_dataEmissao", nullable = false) })
	public Resumo getResumo() {
		return this.resumo;
	}

	public void setResumo(Resumo resumo) {
		this.resumo = resumo;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "baseCalculo", nullable = false, precision = 12, scale = 0)
	public float getBaseCalculo() {
		return this.baseCalculo;
	}

	public void setBaseCalculo(float baseCalculo) {
		this.baseCalculo = baseCalculo;
	}

	@Column(name = "percentual", nullable = false, precision = 12, scale = 0)
	public float getPercentual() {
		return this.percentual;
	}

	public void setPercentual(float percentual) {
		this.percentual = percentual;
	}

	@Column(name = "sinal", nullable = false, length = 1)
	public String getSinal() {
		return this.sinal;
	}

	public void setSinal(String sinal) {
		this.sinal = sinal;
	}

	@Column(name = "valor", nullable = false, precision = 12, scale = 0)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataFim", length = 10)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horaFim", length = 19)
	public Date getHoraFim() {
		return this.horaFim;
	}

	public void setHoraFim(Date horaFim) {
		this.horaFim = horaFim;
	}

	@Column(name = "campoLivreOp", length = 25)
	public String getCampoLivreOp() {
		return this.campoLivreOp;
	}

	public void setCampoLivreOp(String campoLivreOp) {
		this.campoLivreOp = campoLivreOp;
	}

}
