package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoriaservico generated by hbm2java
 */
@Entity
@Table(name = "categoriaservico", catalog = "diteladmdev")
public class Categoriaservico implements java.io.Serializable {

	private int codCatServico;
	private String sigla;
	private String descricao;
	private Set<Servicos> servicoses = new HashSet(0);

	public Categoriaservico() {
	}

	public Categoriaservico(int codCatServico, String sigla, String descricao) {
		this.codCatServico = codCatServico;
		this.sigla = sigla;
		this.descricao = descricao;
	}

	public Categoriaservico(int codCatServico, String sigla, String descricao, Set<Servicos> servicoses) {
		this.codCatServico = codCatServico;
		this.sigla = sigla;
		this.descricao = descricao;
		this.servicoses = servicoses;
	}

	@Id

	@Column(name = "codCatServico", unique = true, nullable = false)
	public int getCodCatServico() {
		return this.codCatServico;
	}

	public void setCodCatServico(int codCatServico) {
		this.codCatServico = codCatServico;
	}

	@Column(name = "sigla", nullable = false, length = 3)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "descricao", nullable = false, length = 25)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaservico")
	public Set<Servicos> getServicoses() {
		return this.servicoses;
	}

	public void setServicoses(Set<Servicos> servicoses) {
		this.servicoses = servicoses;
	}

}
