package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoriadesconto generated by hbm2java
 */
@Entity
@Table(name = "categoriadesconto", catalog = "diteladmdev")
public class Categoriadesconto implements java.io.Serializable {

	private int codCatDesconto;
	private String sigla;
	private String descricao;
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private Set<Descontos> descontoses = new HashSet(0);
	public Categoriadesconto() {
	}

	public Categoriadesconto(int codCatDesconto, String sigla, String descricao) {
		this.codCatDesconto = codCatDesconto;
		this.sigla = sigla;
		this.descricao = descricao;
	}

	public Categoriadesconto(int codCatDesconto, String sigla, String descricao, Set<Descontos> descontoses) {
		this.codCatDesconto = codCatDesconto;
		this.sigla = sigla;
		this.descricao = descricao;
		this.descontoses = descontoses;
	}

	@Id

	@Column(name = "codCatDesconto", unique = true, nullable = false)
	public int getCodCatDesconto() {
		return this.codCatDesconto;
	}

	public void setCodCatDesconto(int codCatDesconto) {
		this.codCatDesconto = codCatDesconto;
	}

	@Column(name = "sigla", nullable = false, length = 3)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "descricao", nullable = false, length = 25)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriadesconto")
	public Set<Descontos> getDescontoses() {
		return this.descontoses;
	}

	public void setDescontoses(Set<Descontos> descontoses) {
		this.descontoses = descontoses;
	}

}
