package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chamadas generated by hbm2java
 */
@Entity
@Table(name = "chamadas", catalog = "diteladmdev")
public class Chamadas implements java.io.Serializable {

	private ChamadasId id;
	private Categoriachamada categoriachamada;
	private Resumo resumo;
	private int cnlAreaLocalUso;
	private int cnlLocalDestino;
	private String nomeLocalDestino;
	private String ufTelDestino;
	private String codNacInt;
	private String codCsp;
	private String nomeOpCsp;
	private Integer codOpRoaming;
	private String opTerminalVincDestino;
	private Date duracaoLigacao;
	private int icms;
	private float valLigImp;
	private float valLigSemImp;
	private int tipoNf;
	private String numNf;
	private String tipoChamada;
	private String grupoHoraTarif;
	private String desHoraTarif;
	private Integer degrauLigacao;
	private String campoLivreOp;

	public Chamadas() {
	}

	public Chamadas(ChamadasId id, Categoriachamada categoriachamada, Resumo resumo, int cnlAreaLocalUso,
			int cnlLocalDestino, String nomeLocalDestino, String ufTelDestino, String codNacInt,
			String opTerminalVincDestino, Date duracaoLigacao, int icms, float valLigImp, float valLigSemImp,
			int tipoNf, String numNf, String tipoChamada) {
		this.id = id;
		this.categoriachamada = categoriachamada;
		this.resumo = resumo;
		this.cnlAreaLocalUso = cnlAreaLocalUso;
		this.cnlLocalDestino = cnlLocalDestino;
		this.nomeLocalDestino = nomeLocalDestino;
		this.ufTelDestino = ufTelDestino;
		this.codNacInt = codNacInt;
		this.opTerminalVincDestino = opTerminalVincDestino;
		this.duracaoLigacao = duracaoLigacao;
		this.icms = icms;
		this.valLigImp = valLigImp;
		this.valLigSemImp = valLigSemImp;
		this.tipoNf = tipoNf;
		this.numNf = numNf;
		this.tipoChamada = tipoChamada;
	}

	public Chamadas(ChamadasId id, Categoriachamada categoriachamada, Resumo resumo, int cnlAreaLocalUso,
			int cnlLocalDestino, String nomeLocalDestino, String ufTelDestino, String codNacInt, String codCsp,
			String nomeOpCsp, Integer codOpRoaming, String opTerminalVincDestino, Date duracaoLigacao, int icms,
			float valLigImp, float valLigSemImp, int tipoNf, String numNf, String tipoChamada, String grupoHoraTarif,
			String desHoraTarif, Integer degrauLigacao, String campoLivreOp) {
		this.id = id;
		this.categoriachamada = categoriachamada;
		this.resumo = resumo;
		this.cnlAreaLocalUso = cnlAreaLocalUso;
		this.cnlLocalDestino = cnlLocalDestino;
		this.nomeLocalDestino = nomeLocalDestino;
		this.ufTelDestino = ufTelDestino;
		this.codNacInt = codNacInt;
		this.codCsp = codCsp;
		this.nomeOpCsp = nomeOpCsp;
		this.codOpRoaming = codOpRoaming;
		this.opTerminalVincDestino = opTerminalVincDestino;
		this.duracaoLigacao = duracaoLigacao;
		this.icms = icms;
		this.valLigImp = valLigImp;
		this.valLigSemImp = valLigSemImp;
		this.tipoNf = tipoNf;
		this.numNf = numNf;
		this.tipoChamada = tipoChamada;
		this.grupoHoraTarif = grupoHoraTarif;
		this.desHoraTarif = desHoraTarif;
		this.degrauLigacao = degrauLigacao;
		this.campoLivreOp = campoLivreOp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idChamadas", column = @Column(name = "idChamadas", nullable = false)),
			@AttributeOverride(name = "numTelefoneChamado", column = @Column(name = "numTelefoneChamado", nullable = false, length = 17)),
			@AttributeOverride(name = "dataLigacao", column = @Column(name = "dataLigacao", nullable = false, length = 10)),
			@AttributeOverride(name = "horaLigacao", column = @Column(name = "horaLigacao", nullable = false, length = 19)),
			@AttributeOverride(name = "categoriaChamadaCodCatChamada", column = @Column(name = "categoriaChamada_codCatChamada", nullable = false)) })
	public ChamadasId getId() {
		return this.id;
	}

	public void setId(ChamadasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoriaChamada_codCatChamada", nullable = false, insertable = false, updatable = false)
	public Categoriachamada getCategoriachamada() {
		return this.categoriachamada;
	}

	public void setCategoriachamada(Categoriachamada categoriachamada) {
		this.categoriachamada = categoriachamada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "resumo_id", referencedColumnName = "id", nullable = false),
			@JoinColumn(name = "resumo_numRecurso", referencedColumnName = "numRecurso", nullable = false),
			@JoinColumn(name = "resumo_fatura_numFatura", referencedColumnName = "fatura_numFatura", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_codCliente", referencedColumnName = "fatura_cliente_codCliente", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_operadora_codOperadora", referencedColumnName = "fatura_cliente_operadora_codOperadora", nullable = false),
			@JoinColumn(name = "resumo_fatura_dataEmissao", referencedColumnName = "fatura_dataEmissao", nullable = false) })
	public Resumo getResumo() {
		return this.resumo;
	}

	public void setResumo(Resumo resumo) {
		this.resumo = resumo;
	}

	@Column(name = "cnlAreaLocalUso", nullable = false)
	public int getCnlAreaLocalUso() {
		return this.cnlAreaLocalUso;
	}

	public void setCnlAreaLocalUso(int cnlAreaLocalUso) {
		this.cnlAreaLocalUso = cnlAreaLocalUso;
	}

	@Column(name = "cnlLocalDestino", nullable = false)
	public int getCnlLocalDestino() {
		return this.cnlLocalDestino;
	}

	public void setCnlLocalDestino(int cnlLocalDestino) {
		this.cnlLocalDestino = cnlLocalDestino;
	}

	@Column(name = "nomeLocalDestino", nullable = false, length = 25)
	public String getNomeLocalDestino() {
		return this.nomeLocalDestino;
	}

	public void setNomeLocalDestino(String nomeLocalDestino) {
		this.nomeLocalDestino = nomeLocalDestino;
	}

	@Column(name = "ufTelDestino", nullable = false, length = 2)
	public String getUfTelDestino() {
		return this.ufTelDestino;
	}

	public void setUfTelDestino(String ufTelDestino) {
		this.ufTelDestino = ufTelDestino;
	}

	@Column(name = "codNacInt", nullable = false, length = 2)
	public String getCodNacInt() {
		return this.codNacInt;
	}

	public void setCodNacInt(String codNacInt) {
		this.codNacInt = codNacInt;
	}

	@Column(name = "codCsp", length = 2)
	public String getCodCsp() {
		return this.codCsp;
	}

	public void setCodCsp(String codCsp) {
		this.codCsp = codCsp;
	}

	@Column(name = "nomeOpCsp", length = 20)
	public String getNomeOpCsp() {
		return this.nomeOpCsp;
	}

	public void setNomeOpCsp(String nomeOpCsp) {
		this.nomeOpCsp = nomeOpCsp;
	}

	@Column(name = "codOpRoaming")
	public Integer getCodOpRoaming() {
		return this.codOpRoaming;
	}

	public void setCodOpRoaming(Integer codOpRoaming) {
		this.codOpRoaming = codOpRoaming;
	}

	@Column(name = "opTerminalVincDestino", nullable = false, length = 3)
	public String getOpTerminalVincDestino() {
		return this.opTerminalVincDestino;
	}

	public void setOpTerminalVincDestino(String opTerminalVincDestino) {
		this.opTerminalVincDestino = opTerminalVincDestino;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "duracaoLigacao", nullable = false, length = 19)
	public Date getDuracaoLigacao() {
		return this.duracaoLigacao;
	}

	public void setDuracaoLigacao(Date duracaoLigacao) {
		this.duracaoLigacao = duracaoLigacao;
	}

	@Column(name = "icms", nullable = false)
	public int getIcms() {
		return this.icms;
	}

	public void setIcms(int icms) {
		this.icms = icms;
	}

	@Column(name = "valLigImp", nullable = false, precision = 12, scale = 0)
	public float getValLigImp() {
		return this.valLigImp;
	}

	public void setValLigImp(float valLigImp) {
		this.valLigImp = valLigImp;
	}

	@Column(name = "valLigSemImp", nullable = false, precision = 12, scale = 0)
	public float getValLigSemImp() {
		return this.valLigSemImp;
	}

	public void setValLigSemImp(float valLigSemImp) {
		this.valLigSemImp = valLigSemImp;
	}

	@Column(name = "tipoNF", nullable = false)
	public int getTipoNf() {
		return this.tipoNf;
	}

	public void setTipoNf(int tipoNf) {
		this.tipoNf = tipoNf;
	}

	@Column(name = "numNF", nullable = false, length = 12)
	public String getNumNf() {
		return this.numNf;
	}

	public void setNumNf(String numNf) {
		this.numNf = numNf;
	}

	@Column(name = "tipoChamada", nullable = false, length = 1)
	public String getTipoChamada() {
		return this.tipoChamada;
	}

	public void setTipoChamada(String tipoChamada) {
		this.tipoChamada = tipoChamada;
	}

	@Column(name = "grupoHoraTarif", length = 1)
	public String getGrupoHoraTarif() {
		return this.grupoHoraTarif;
	}

	public void setGrupoHoraTarif(String grupoHoraTarif) {
		this.grupoHoraTarif = grupoHoraTarif;
	}

	@Column(name = "desHoraTarif", length = 15)
	public String getDesHoraTarif() {
		return this.desHoraTarif;
	}

	public void setDesHoraTarif(String desHoraTarif) {
		this.desHoraTarif = desHoraTarif;
	}

	@Column(name = "degrauLigacao")
	public Integer getDegrauLigacao() {
		return this.degrauLigacao;
	}

	public void setDegrauLigacao(Integer degrauLigacao) {
		this.degrauLigacao = degrauLigacao;
	}

	@Column(name = "campoLivreOp", length = 25)
	public String getCampoLivreOp() {
		return this.campoLivreOp;
	}

	public void setCampoLivreOp(String campoLivreOp) {
		this.campoLivreOp = campoLivreOp;
	}

}
