package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "diteladmdev")
public class Cliente implements java.io.Serializable {

	private ClienteId id;
	private Operadora operadora;
	private String nome;
	private String cnpj;
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private Set<Fatura> faturas = new HashSet(0);

	public Cliente() {
	}

	public Cliente(ClienteId id, Operadora operadora, String nome, String cnpj) {
		this.id = id;
		this.operadora = operadora;
		this.nome = nome;
		this.cnpj = cnpj;
	}

	public Cliente(ClienteId id, Operadora operadora, String nome, String cnpj, Set<Fatura> faturas) {
		this.id = id;
		this.operadora = operadora;
		this.nome = nome;
		this.cnpj = cnpj;
		this.faturas = faturas;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codCliente", column = @Column(name = "codCliente", nullable = false, length = 15)),
			@AttributeOverride(name = "operadoraCodOperadora", column = @Column(name = "operadora_codOperadora", nullable = false)) })
	public ClienteId getId() {
		return this.id;
	}

	public void setId(ClienteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operadora_codOperadora", nullable = false, insertable = false, updatable = false)
	public Operadora getOperadora() {
		return this.operadora;
	}

	public void setOperadora(Operadora operadora) {
		this.operadora = operadora;
	}

	@Column(name = "nome", nullable = false, length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cnpj", nullable = false, length = 16777215)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Fatura> getFaturas() {
		return this.faturas;
	}

	public void setFaturas(Set<Fatura> faturas) {
		this.faturas = faturas;
	}

}
