package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DescontosId generated by hbm2java
 */
@Embeddable
public class DescontosId implements java.io.Serializable {

	private String idDescontos;
	private Date dataInicio;
	private Date horaInicio;
	private int categoriaDescontoCodCatDesconto;

	public DescontosId() {
	}

	public DescontosId(String idDescontos, Date dataInicio, Date horaInicio, int categoriaDescontoCodCatDesconto) {
		this.idDescontos = idDescontos;
		this.dataInicio = dataInicio;
		this.horaInicio = horaInicio;
		this.categoriaDescontoCodCatDesconto = categoriaDescontoCodCatDesconto;
	}

	@Column(name = "idDescontos", nullable = false)
	public String getIdDescontos() {
		return this.idDescontos;
	}

	public void setIdDescontos(String idDescontos) {
		this.idDescontos = idDescontos;
	}

	@Column(name = "dataInicio", nullable = false, length = 10)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Column(name = "horaInicio", nullable = false, length = 19)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Column(name = "categoriaDesconto_codCatDesconto", nullable = false)
	public int getCategoriaDescontoCodCatDesconto() {
		return this.categoriaDescontoCodCatDesconto;
	}

	public void setCategoriaDescontoCodCatDesconto(int categoriaDescontoCodCatDesconto) {
		this.categoriaDescontoCodCatDesconto = categoriaDescontoCodCatDesconto;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DescontosId))
			return false;
		DescontosId castOther = (DescontosId) other;

		return (this.getIdDescontos() == castOther.getIdDescontos())
				&& ((this.getDataInicio() == castOther.getDataInicio()) || (this.getDataInicio() != null
						&& castOther.getDataInicio() != null && this.getDataInicio().equals(castOther.getDataInicio())))
				&& ((this.getHoraInicio() == castOther.getHoraInicio()) || (this.getHoraInicio() != null
						&& castOther.getHoraInicio() != null && this.getHoraInicio().equals(castOther.getHoraInicio())))
				&& (this.getCategoriaDescontoCodCatDesconto() == castOther.getCategoriaDescontoCodCatDesconto());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDescontos() == null ? 0 : this.getIdDescontos().hashCode());
		result = 37 * result + (getDataInicio() == null ? 0 : this.getDataInicio().hashCode());
		result = 37 * result + (getHoraInicio() == null ? 0 : this.getHoraInicio().hashCode());
		result = 37 * result + this.getCategoriaDescontoCodCatDesconto();
		return result;
	}

}
