package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Descontos generated by hbm2java
 */
@Entity
@Table(name = "descontos", catalog = "diteladmdev")
public class Descontos implements java.io.Serializable {

	private DescontosId id;
	private Categoriadesconto categoriadesconto;
	private Resumo resumo;
	private String tipo;
	private float baseCal;
	private int tipoNf;
	private String numNf;
	private Float percentual;
	private String sinal;
	private float valor;
	private Date dataFim;
	private Date horaFim;
	private String campoLivreOp;

	public Descontos() {
	}

	public Descontos(DescontosId id, Categoriadesconto categoriadesconto, Resumo resumo, String tipo, float baseCal,
			int tipoNf, String numNf, String sinal, float valor) {
		this.id = id;
		this.categoriadesconto = categoriadesconto;
		this.resumo = resumo;
		this.tipo = tipo;
		this.baseCal = baseCal;
		this.tipoNf = tipoNf;
		this.numNf = numNf;
		this.sinal = sinal;
		this.valor = valor;
	}

	public Descontos(DescontosId id, Categoriadesconto categoriadesconto, Resumo resumo, String tipo, float baseCal,
			int tipoNf, String numNf, Float percentual, String sinal, float valor, Date dataFim, Date horaFim,
			String campoLivreOp) {
		this.id = id;
		this.categoriadesconto = categoriadesconto;
		this.resumo = resumo;
		this.tipo = tipo;
		this.baseCal = baseCal;
		this.tipoNf = tipoNf;
		this.numNf = numNf;
		this.percentual = percentual;
		this.sinal = sinal;
		this.valor = valor;
		this.dataFim = dataFim;
		this.horaFim = horaFim;
		this.campoLivreOp = campoLivreOp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDescontos", column = @Column(name = "idDescontos", nullable = false)),
			@AttributeOverride(name = "dataInicio", column = @Column(name = "dataInicio", nullable = false, length = 10)),
			@AttributeOverride(name = "horaInicio", column = @Column(name = "horaInicio", nullable = false, length = 19)),
			@AttributeOverride(name = "categoriaDescontoCodCatDesconto", column = @Column(name = "categoriaDesconto_codCatDesconto", nullable = false)) })
	public DescontosId getId() {
		return this.id;
	}

	public void setId(DescontosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoriaDesconto_codCatDesconto", nullable = false, insertable = false, updatable = false)
	public Categoriadesconto getCategoriadesconto() {
		return this.categoriadesconto;
	}

	public void setCategoriadesconto(Categoriadesconto categoriadesconto) {
		this.categoriadesconto = categoriadesconto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "resumo_id", referencedColumnName = "id", nullable = false),
			@JoinColumn(name = "resumo_numRecurso", referencedColumnName = "numRecurso", nullable = false),
			@JoinColumn(name = "resumo_fatura_numFatura", referencedColumnName = "fatura_numFatura", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_codCliente", referencedColumnName = "fatura_cliente_codCliente", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_operadora_codOperadora", referencedColumnName = "fatura_cliente_operadora_codOperadora", nullable = false),
			@JoinColumn(name = "resumo_fatura_dataEmissao", referencedColumnName = "fatura_dataEmissao", nullable = false) })
	public Resumo getResumo() {
		return this.resumo;
	}

	public void setResumo(Resumo resumo) {
		this.resumo = resumo;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "baseCal", nullable = false, precision = 12, scale = 0)
	public float getBaseCal() {
		return this.baseCal;
	}

	public void setBaseCal(float baseCal) {
		this.baseCal = baseCal;
	}

	@Column(name = "tipoNF", nullable = false)
	public int getTipoNf() {
		return this.tipoNf;
	}

	public void setTipoNf(int tipoNf) {
		this.tipoNf = tipoNf;
	}

	@Column(name = "numNF", nullable = false, length = 12)
	public String getNumNf() {
		return this.numNf;
	}

	public void setNumNf(String numNf) {
		this.numNf = numNf;
	}

	@Column(name = "percentual", precision = 12, scale = 0)
	public Float getPercentual() {
		return this.percentual;
	}

	public void setPercentual(Float percentual) {
		this.percentual = percentual;
	}

	@Column(name = "sinal", nullable = false, length = 1)
	public String getSinal() {
		return this.sinal;
	}

	public void setSinal(String sinal) {
		this.sinal = sinal;
	}

	@Column(name = "valor", nullable = false, precision = 12, scale = 0)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataFim", length = 10)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "horaFim", length = 19)
	public Date getHoraFim() {
		return this.horaFim;
	}

	public void setHoraFim(Date horaFim) {
		this.horaFim = horaFim;
	}

	@Column(name = "campoLivreOp", length = 25)
	public String getCampoLivreOp() {
		return this.campoLivreOp;
	}

	public void setCampoLivreOp(String campoLivreOp) {
		this.campoLivreOp = campoLivreOp;
	}

}
