package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Enderecos generated by hbm2java
 */
@Entity
@Table(name = "enderecos", catalog = "diteladmdev")
public class Enderecos implements java.io.Serializable {

	private EnderecosId id;
	private Fatura fatura;
	private String tipoEndereco;
	private String cnlRecEnd;
	private String nomeLocalEnd;
	private String ufLocal;
	private String endereco;
	private String numero;
	private String complemento;
	private String bairro;
	private String campoLivreOp;

	public Enderecos() {
	}

	public Enderecos(EnderecosId id, Fatura fatura) {
		this.id = id;
		this.fatura = fatura;
	}

	public Enderecos(EnderecosId id, Fatura fatura, String tipoEndereco, String cnlRecEnd, String nomeLocalEnd,
			String ufLocal, String endereco, String numero, String complemento, String bairro, String campoLivreOp) {
		this.id = id;
		this.fatura = fatura;
		this.tipoEndereco = tipoEndereco;
		this.cnlRecEnd = cnlRecEnd;
		this.nomeLocalEnd = nomeLocalEnd;
		this.ufLocal = ufLocal;
		this.endereco = endereco;
		this.numero = numero;
		this.complemento = complemento;
		this.bairro = bairro;
		this.campoLivreOp = campoLivreOp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idEnderecos", column = @Column(name = "idEnderecos", nullable = false)),
			@AttributeOverride(name = "faturaNumFatura", column = @Column(name = "fatura_numFatura", nullable = false)),
			@AttributeOverride(name = "faturaClienteCodCliente", column = @Column(name = "fatura_cliente_codCliente", nullable = false, length = 15)),
			@AttributeOverride(name = "faturaClienteOperadoraCodOperadora", column = @Column(name = "fatura_cliente_operadora_codOperadora", nullable = false)),
			@AttributeOverride(name = "faturaDataEmissao", column = @Column(name = "fatura_dataEmissao", nullable = false, length = 10)) })
	public EnderecosId getId() {
		return this.id;
	}

	public void setId(EnderecosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "fatura_numFatura", referencedColumnName = "numFatura", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "fatura_cliente_codCliente", referencedColumnName = "cliente_codCliente", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "fatura_cliente_operadora_codOperadora", referencedColumnName = "cliente_operadora_codOperadora", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "fatura_dataEmissao", referencedColumnName = "dataEmissao", nullable = false, insertable = false, updatable = false) })
	public Fatura getFatura() {
		return this.fatura;
	}

	public void setFatura(Fatura fatura) {
		this.fatura = fatura;
	}

	@Column(name = "tipoEndereco", length = 5)
	public String getTipoEndereco() {
		return this.tipoEndereco;
	}

	public void setTipoEndereco(String tipoEndereco) {
		this.tipoEndereco = tipoEndereco;
	}

	@Column(name = "cnlRecEnd", length = 5)
	public String getCnlRecEnd() {
		return this.cnlRecEnd;
	}

	public void setCnlRecEnd(String cnlRecEnd) {
		this.cnlRecEnd = cnlRecEnd;
	}

	@Column(name = "nomeLocalEnd", length = 15)
	public String getNomeLocalEnd() {
		return this.nomeLocalEnd;
	}

	public void setNomeLocalEnd(String nomeLocalEnd) {
		this.nomeLocalEnd = nomeLocalEnd;
	}

	@Column(name = "ufLocal", length = 2)
	public String getUfLocal() {
		return this.ufLocal;
	}

	public void setUfLocal(String ufLocal) {
		this.ufLocal = ufLocal;
	}

	@Column(name = "endereco", length = 30)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "numero", length = 5)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "complemento", length = 8)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "bairro", length = 10)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "campoLivreOp", length = 25)
	public String getCampoLivreOp() {
		return this.campoLivreOp;
	}

	public void setCampoLivreOp(String campoLivreOp) {
		this.campoLivreOp = campoLivreOp;
	}

}
