package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServicosId generated by hbm2java
 */
@Embeddable
public class ServicosId implements java.io.Serializable {

	private int idServicos;
	private Date dataServico;
	private Date horaServico;
	private int categoriaServicoCodCatServico;

	public ServicosId() {
	}

	public ServicosId(int idServicos, Date dataServico, Date horaServico, int categoriaServicoCodCatServico) {
		this.idServicos = idServicos;
		this.dataServico = dataServico;
		this.horaServico = horaServico;
		this.categoriaServicoCodCatServico = categoriaServicoCodCatServico;
	}

	@Column(name = "idServicos", nullable = false)
	public int getIdServicos() {
		return this.idServicos;
	}

	public void setIdServicos(int idServicos) {
		this.idServicos = idServicos;
	}

	@Column(name = "dataServico", nullable = false, length = 10)
	public Date getDataServico() {
		return this.dataServico;
	}

	public void setDataServico(Date dataServico) {
		this.dataServico = dataServico;
	}

	@Column(name = "horaServico", nullable = false, length = 19)
	public Date getHoraServico() {
		return this.horaServico;
	}

	public void setHoraServico(Date horaServico) {
		this.horaServico = horaServico;
	}

	@Column(name = "categoriaServico_codCatServico", nullable = false)
	public int getCategoriaServicoCodCatServico() {
		return this.categoriaServicoCodCatServico;
	}

	public void setCategoriaServicoCodCatServico(int categoriaServicoCodCatServico) {
		this.categoriaServicoCodCatServico = categoriaServicoCodCatServico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServicosId))
			return false;
		ServicosId castOther = (ServicosId) other;

		return (this.getIdServicos() == castOther.getIdServicos())
				&& ((this.getDataServico() == castOther.getDataServico())
						|| (this.getDataServico() != null && castOther.getDataServico() != null
								&& this.getDataServico().equals(castOther.getDataServico())))
				&& ((this.getHoraServico() == castOther.getHoraServico())
						|| (this.getHoraServico() != null && castOther.getHoraServico() != null
								&& this.getHoraServico().equals(castOther.getHoraServico())))
				&& (this.getCategoriaServicoCodCatServico() == castOther.getCategoriaServicoCodCatServico());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdServicos();
		result = 37 * result + (getDataServico() == null ? 0 : this.getDataServico().hashCode());
		result = 37 * result + (getHoraServico() == null ? 0 : this.getHoraServico().hashCode());
		result = 37 * result + this.getCategoriaServicoCodCatServico();
		return result;
	}

}
