package br.gov.cultura.DitelAdm.modelo;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Servicos generated by hbm2java
 */
@Entity
@Table(name = "servicos", catalog = "diteladmdev")
public class Servicos implements java.io.Serializable {

	private ServicosId id;
	private Categoriaservico categoriaservico;
	private Resumo resumo;
	private Integer cnlAreaLocalUso;
	private String codNacInt;
	private String numTelDestino;
	private Integer codOpRoaming;
	private String opTerminalVincDestino;
	private int quantUtil;
	private String unidadeServico;
	private float valServImp;
	private float valServ;
	private int tipoNf;
	private String numNf;
	private String campoLivreOp;

	public Servicos() {
	}

	public Servicos(ServicosId id, Categoriaservico categoriaservico, Resumo resumo, String codNacInt, int quantUtil,
			String unidadeServico, float valServImp, float valServ, int tipoNf, String numNf) {
		this.id = id;
		this.categoriaservico = categoriaservico;
		this.resumo = resumo;
		this.codNacInt = codNacInt;
		this.quantUtil = quantUtil;
		this.unidadeServico = unidadeServico;
		this.valServImp = valServImp;
		this.valServ = valServ;
		this.tipoNf = tipoNf;
		this.numNf = numNf;
	}

	public Servicos(ServicosId id, Categoriaservico categoriaservico, Resumo resumo, Integer cnlAreaLocalUso,
			String codNacInt, String numTelDestino, Integer codOpRoaming, String opTerminalVincDestino, int quantUtil,
			String unidadeServico, float valServImp, float valServ, int tipoNf, String numNf, String campoLivreOp) {
		this.id = id;
		this.categoriaservico = categoriaservico;
		this.resumo = resumo;
		this.cnlAreaLocalUso = cnlAreaLocalUso;
		this.codNacInt = codNacInt;
		this.numTelDestino = numTelDestino;
		this.codOpRoaming = codOpRoaming;
		this.opTerminalVincDestino = opTerminalVincDestino;
		this.quantUtil = quantUtil;
		this.unidadeServico = unidadeServico;
		this.valServImp = valServImp;
		this.valServ = valServ;
		this.tipoNf = tipoNf;
		this.numNf = numNf;
		this.campoLivreOp = campoLivreOp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idServicos", column = @Column(name = "idServicos", nullable = false)),
			@AttributeOverride(name = "dataServico", column = @Column(name = "dataServico", nullable = false, length = 10)),
			@AttributeOverride(name = "horaServico", column = @Column(name = "horaServico", nullable = false, length = 19)),
			@AttributeOverride(name = "categoriaServicoCodCatServico", column = @Column(name = "categoriaServico_codCatServico", nullable = false)) })
	public ServicosId getId() {
		return this.id;
	}

	public void setId(ServicosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoriaServico_codCatServico", nullable = false, insertable = false, updatable = false)
	public Categoriaservico getCategoriaservico() {
		return this.categoriaservico;
	}

	public void setCategoriaservico(Categoriaservico categoriaservico) {
		this.categoriaservico = categoriaservico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "resumo_id", referencedColumnName = "id", nullable = false),
			@JoinColumn(name = "resumo_numRecurso", referencedColumnName = "numRecurso", nullable = false),
			@JoinColumn(name = "resumo_fatura_numFatura", referencedColumnName = "fatura_numFatura", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_codCliente", referencedColumnName = "fatura_cliente_codCliente", nullable = false),
			@JoinColumn(name = "resumo_fatura_cliente_operadora_codOperadora", referencedColumnName = "fatura_cliente_operadora_codOperadora", nullable = false),
			@JoinColumn(name = "resumo_fatura_dataEmissao", referencedColumnName = "fatura_dataEmissao", nullable = false) })
	public Resumo getResumo() {
		return this.resumo;
	}

	public void setResumo(Resumo resumo) {
		this.resumo = resumo;
	}

	@Column(name = "cnlAreaLocalUso")
	public Integer getCnlAreaLocalUso() {
		return this.cnlAreaLocalUso;
	}

	public void setCnlAreaLocalUso(Integer cnlAreaLocalUso) {
		this.cnlAreaLocalUso = cnlAreaLocalUso;
	}

	@Column(name = "codNacInt", nullable = false, length = 2)
	public String getCodNacInt() {
		return this.codNacInt;
	}

	public void setCodNacInt(String codNacInt) {
		this.codNacInt = codNacInt;
	}

	@Column(name = "numTelDestino", length = 17)
	public String getNumTelDestino() {
		return this.numTelDestino;
	}

	public void setNumTelDestino(String numTelDestino) {
		this.numTelDestino = numTelDestino;
	}

	@Column(name = "codOpRoaming")
	public Integer getCodOpRoaming() {
		return this.codOpRoaming;
	}

	public void setCodOpRoaming(Integer codOpRoaming) {
		this.codOpRoaming = codOpRoaming;
	}

	@Column(name = "opTerminalVincDestino", length = 3)
	public String getOpTerminalVincDestino() {
		return this.opTerminalVincDestino;
	}

	public void setOpTerminalVincDestino(String opTerminalVincDestino) {
		this.opTerminalVincDestino = opTerminalVincDestino;
	}

	@Column(name = "quantUtil", nullable = false)
	public int getQuantUtil() {
		return this.quantUtil;
	}

	public void setQuantUtil(int quantUtil) {
		this.quantUtil = quantUtil;
	}

	@Column(name = "unidadeServico", nullable = false, length = 2)
	public String getUnidadeServico() {
		return this.unidadeServico;
	}

	public void setUnidadeServico(String unidadeServico) {
		this.unidadeServico = unidadeServico;
	}

	@Column(name = "valServImp", nullable = false, precision = 12, scale = 0)
	public float getValServImp() {
		return this.valServImp;
	}

	public void setValServImp(float valServImp) {
		this.valServImp = valServImp;
	}

	@Column(name = "valServ", nullable = false, precision = 12, scale = 0)
	public float getValServ() {
		return this.valServ;
	}

	public void setValServ(float valServ) {
		this.valServ = valServ;
	}

	@Column(name = "tipoNF", nullable = false)
	public int getTipoNf() {
		return this.tipoNf;
	}

	public void setTipoNf(int tipoNf) {
		this.tipoNf = tipoNf;
	}

	@Column(name = "numNF", nullable = false, length = 12)
	public String getNumNf() {
		return this.numNf;
	}

	public void setNumNf(String numNf) {
		this.numNf = numNf;
	}

	@Column(name = "campoLivreOp", length = 25)
	public String getCampoLivreOp() {
		return this.campoLivreOp;
	}

	public void setCampoLivreOp(String campoLivreOp) {
		this.campoLivreOp = campoLivreOp;
	}

}
