package br.gov.cultura.DitelAdm.model.faturasV3;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClienteId generated by hbm2java
 */
@Embeddable
public class ClienteId implements java.io.Serializable {

	private String codCliente;
	private int operadoraCodOperadora;

	public ClienteId() {
	}

	public ClienteId(String codCliente, int operadoraCodOperadora) {
		this.codCliente = codCliente;
		this.operadoraCodOperadora = operadoraCodOperadora;
	}

	@Column(name = "codCliente", nullable = false, length = 15)
	public String getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(String codCliente) {
		this.codCliente = codCliente;
	}

	@Column(name = "operadora_codOperadora", nullable = false)
	public int getOperadoraCodOperadora() {
		return this.operadoraCodOperadora;
	}

	public void setOperadoraCodOperadora(int operadoraCodOperadora) {
		this.operadoraCodOperadora = operadoraCodOperadora;
	}
@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteId))
			return false;
		ClienteId castOther = (ClienteId) other;

		return ((this.getCodCliente() == castOther.getCodCliente()) || (this.getCodCliente() != null
				&& castOther.getCodCliente() != null && this.getCodCliente().equals(castOther.getCodCliente())))
				&& (this.getOperadoraCodOperadora() == castOther.getOperadoraCodOperadora());
	}
@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodCliente() == null ? 0 : this.getCodCliente().hashCode());
		result = 37 * result + this.getOperadoraCodOperadora();
		return result;
	}

}
