package br.gov.cultura.DitelAdm.model.faturasV3;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FaturaId generated by hbm2java
 */
@Embeddable
public class FaturaId implements java.io.Serializable {

	private int numFatura;
	private String clienteCodCliente;
	private int clienteOperadoraCodOperadora;
	private Date dataEmissao;

	public FaturaId() {
	}

	public FaturaId(int numFatura, String clienteCodCliente, int clienteOperadoraCodOperadora, Date dataEmissao) {
		this.numFatura = numFatura;
		this.clienteCodCliente = clienteCodCliente;
		this.clienteOperadoraCodOperadora = clienteOperadoraCodOperadora;
		this.dataEmissao = dataEmissao;
	}

	@Column(name = "numFatura", nullable = false)
	public int getNumFatura() {
		return this.numFatura;
	}

	public void setNumFatura(int numFatura) {
		this.numFatura = numFatura;
	}

	@Column(name = "cliente_codCliente", nullable = false, length = 15)
	public String getClienteCodCliente() {
		return this.clienteCodCliente;
	}

	public void setClienteCodCliente(String clienteCodCliente) {
		this.clienteCodCliente = clienteCodCliente;
	}

	@Column(name = "cliente_operadora_codOperadora", nullable = false)
	public int getClienteOperadoraCodOperadora() {
		return this.clienteOperadoraCodOperadora;
	}

	public void setClienteOperadoraCodOperadora(int clienteOperadoraCodOperadora) {
		this.clienteOperadoraCodOperadora = clienteOperadoraCodOperadora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataEmissao", nullable = false, length = 10)
	public Date getDataEmissao() {
		return this.dataEmissao;
	}

	public void setDataEmissao(Date dataEmissao) {
		this.dataEmissao = dataEmissao;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FaturaId))
			return false;
		FaturaId castOther = (FaturaId) other;

		return (this.getNumFatura() == castOther.getNumFatura())
				&& ((this.getClienteCodCliente() == castOther.getClienteCodCliente())
						|| (this.getClienteCodCliente() != null && castOther.getClienteCodCliente() != null
								&& this.getClienteCodCliente().equals(castOther.getClienteCodCliente())))
				&& (this.getClienteOperadoraCodOperadora() == castOther.getClienteOperadoraCodOperadora())
				&& ((this.getDataEmissao() == castOther.getDataEmissao())
						|| (this.getDataEmissao() != null && castOther.getDataEmissao() != null
								&& this.getDataEmissao().equals(castOther.getDataEmissao())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumFatura();
		result = 37 * result + (getClienteCodCliente() == null ? 0 : this.getClienteCodCliente().hashCode());
		result = 37 * result + this.getClienteOperadoraCodOperadora();
		result = 37 * result + (getDataEmissao() == null ? 0 : this.getDataEmissao().hashCode());
		return result;
	}

}
