package br.gov.cultura.DitelAdm.model.faturasV3;
// Generated 05/07/2016 12:36:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanosId generated by hbm2java
 */
@Embeddable
public class PlanosId implements java.io.Serializable {

	private int idPlanos;
	private Date dataIniCiclo;
	private int categoriaPlanoCodCatPlano;
	private int resumoId;
	private String resumoNumRecurso;
	private int resumoFaturaNumFatura;
	private String resumoFaturaClienteCodCliente;
	private int resumoFaturaClienteOperadoraCodOperadora;
	private Date resumoFaturaDataEmissao;

	public PlanosId() {
	}

	public PlanosId(int idPlanos, Date dataIniCiclo, int categoriaPlanoCodCatPlano, int resumoId,
			String resumoNumRecurso, int resumoFaturaNumFatura, String resumoFaturaClienteCodCliente,
			int resumoFaturaClienteOperadoraCodOperadora, Date resumoFaturaDataEmissao) {
		this.idPlanos = idPlanos;
		this.dataIniCiclo = dataIniCiclo;
		this.categoriaPlanoCodCatPlano = categoriaPlanoCodCatPlano;
		this.resumoId = resumoId;
		this.resumoNumRecurso = resumoNumRecurso;
		this.resumoFaturaNumFatura = resumoFaturaNumFatura;
		this.resumoFaturaClienteCodCliente = resumoFaturaClienteCodCliente;
		this.resumoFaturaClienteOperadoraCodOperadora = resumoFaturaClienteOperadoraCodOperadora;
		this.resumoFaturaDataEmissao = resumoFaturaDataEmissao;
	}

	@Column(name = "idPlanos", nullable = false)
	public int getIdPlanos() {
		return this.idPlanos;
	}

	public void setIdPlanos(int idPlanos) {
		this.idPlanos = idPlanos;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dataIniCiclo", nullable = false, length = 10)
	public Date getDataIniCiclo() {
		return this.dataIniCiclo;
	}

	public void setDataIniCiclo(Date dataIniCiclo) {
		this.dataIniCiclo = dataIniCiclo;
	}

	@Column(name = "categoriaPlano_codCatPlano", nullable = false)
	public int getCategoriaPlanoCodCatPlano() {
		return this.categoriaPlanoCodCatPlano;
	}

	public void setCategoriaPlanoCodCatPlano(int categoriaPlanoCodCatPlano) {
		this.categoriaPlanoCodCatPlano = categoriaPlanoCodCatPlano;
	}

	@Column(name = "resumo_id", nullable = false)
	public int getResumoId() {
		return this.resumoId;
	}

	public void setResumoId(int resumoId) {
		this.resumoId = resumoId;
	}

	@Column(name = "resumo_numRecurso", nullable = false, length = 20)
	public String getResumoNumRecurso() {
		return this.resumoNumRecurso;
	}

	public void setResumoNumRecurso(String resumoNumRecurso) {
		this.resumoNumRecurso = resumoNumRecurso;
	}

	@Column(name = "resumo_fatura_numFatura", nullable = false)
	public int getResumoFaturaNumFatura() {
		return this.resumoFaturaNumFatura;
	}

	public void setResumoFaturaNumFatura(int resumoFaturaNumFatura) {
		this.resumoFaturaNumFatura = resumoFaturaNumFatura;
	}

	@Column(name = "resumo_fatura_cliente_codCliente", nullable = false, length = 15)
	public String getResumoFaturaClienteCodCliente() {
		return this.resumoFaturaClienteCodCliente;
	}

	public void setResumoFaturaClienteCodCliente(String resumoFaturaClienteCodCliente) {
		this.resumoFaturaClienteCodCliente = resumoFaturaClienteCodCliente;
	}

	@Column(name = "resumo_fatura_cliente_operadora_codOperadora", nullable = false)
	public int getResumoFaturaClienteOperadoraCodOperadora() {
		return this.resumoFaturaClienteOperadoraCodOperadora;
	}

	public void setResumoFaturaClienteOperadoraCodOperadora(int resumoFaturaClienteOperadoraCodOperadora) {
		this.resumoFaturaClienteOperadoraCodOperadora = resumoFaturaClienteOperadoraCodOperadora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "resumo_fatura_dataEmissao", nullable = false, length = 10)
	public Date getResumoFaturaDataEmissao() {
		return this.resumoFaturaDataEmissao;
	}

	public void setResumoFaturaDataEmissao(Date resumoFaturaDataEmissao) {
		this.resumoFaturaDataEmissao = resumoFaturaDataEmissao;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlanosId))
			return false;
		PlanosId castOther = (PlanosId) other;

		return (this.getIdPlanos() == castOther.getIdPlanos())
				&& ((this.getDataIniCiclo() == castOther.getDataIniCiclo())
						|| (this.getDataIniCiclo() != null && castOther.getDataIniCiclo() != null
								&& this.getDataIniCiclo().equals(castOther.getDataIniCiclo())))
				&& (this.getCategoriaPlanoCodCatPlano() == castOther.getCategoriaPlanoCodCatPlano())
				&& (this.getResumoId() == castOther.getResumoId())
				&& ((this.getResumoNumRecurso() == castOther.getResumoNumRecurso())
						|| (this.getResumoNumRecurso() != null && castOther.getResumoNumRecurso() != null
								&& this.getResumoNumRecurso().equals(castOther.getResumoNumRecurso())))
				&& (this.getResumoFaturaNumFatura() == castOther.getResumoFaturaNumFatura())
				&& ((this.getResumoFaturaClienteCodCliente() == castOther.getResumoFaturaClienteCodCliente())
						|| (this.getResumoFaturaClienteCodCliente() != null
								&& castOther.getResumoFaturaClienteCodCliente() != null
								&& this.getResumoFaturaClienteCodCliente()
										.equals(castOther.getResumoFaturaClienteCodCliente())))
				&& (this.getResumoFaturaClienteOperadoraCodOperadora() == castOther
						.getResumoFaturaClienteOperadoraCodOperadora())
				&& ((this.getResumoFaturaDataEmissao() == castOther.getResumoFaturaDataEmissao())
						|| (this.getResumoFaturaDataEmissao() != null && castOther.getResumoFaturaDataEmissao() != null
								&& this.getResumoFaturaDataEmissao().equals(castOther.getResumoFaturaDataEmissao())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPlanos();
		result = 37 * result + (getDataIniCiclo() == null ? 0 : this.getDataIniCiclo().hashCode());
		result = 37 * result + this.getCategoriaPlanoCodCatPlano();
		result = 37 * result + this.getResumoId();
		result = 37 * result + (getResumoNumRecurso() == null ? 0 : this.getResumoNumRecurso().hashCode());
		result = 37 * result + this.getResumoFaturaNumFatura();
		result = 37 * result
				+ (getResumoFaturaClienteCodCliente() == null ? 0 : this.getResumoFaturaClienteCodCliente().hashCode());
		result = 37 * result + this.getResumoFaturaClienteOperadoraCodOperadora();
		result = 37 * result
				+ (getResumoFaturaDataEmissao() == null ? 0 : this.getResumoFaturaDataEmissao().hashCode());
		return result;
	}

}
